{% set name = "mkdocs-material" %}
{% set version = "9.4.3" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs_material-{{ version }}.tar.gz
  sha256: 5c9abc3f6ba8f88be1f9f13df23d695ca4dddbdd8a3538e4e6279c055c3936bc


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-nodejs-version >=0.3.0
    - hatch-requirements-txt
    - hatchling
    - pip
    - python >=3.8
  run:
    - babel ~=2.10
    - colorama ~=0.4
    - jinja2 ~=3.0
    - markdown ~=3.2
    - mkdocs ~=1.5
    - mkdocs-material-extensions ~=1.1
    - paginate ~=0.5
    - pygments ~=2.16
    - pymdown-extensions ~=10.2
    - python >=3.8
    - regex ~=2022.4
    - requests ~=2.26

test:
  imports:
    - material
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://squidfunk.github.io/mkdocs-material/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Material Design theme for mkdocs
  doc_url: https://squidfunk.github.io/mkdocs-material/
  dev_url: https://squidfunk.github.io/mkdocs-material/customization/

extra:
  recipe-maintainers:
    - monaldoj
    - marcelotrevisani
    - thewchan
