{% set name = "mkdocs-material" %}
{% set version = "9.2.4" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs_material-{{ version }}.tar.gz
  sha256: 25008187b89fc376cb4ed2312b1fea4121bf2bd956442f38afdc6b4dcc21c57d


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - hatch-nodejs-version >=0.3.0
    - hatch-requirements-txt
    - hatchling
    - pip
    - python >=3.7
  run:
    - babel >=2.10.3
    - colorama >=0.4
    - jinja2 >=3.0
    - lxml >=4.6
    - markdown >=3.2
    - mkdocs >=1.5.2
    - mkdocs-material-extensions >=1.1
    - paginate >=0.5.6
    - pygments >=2.14
    - pymdown-extensions >=9.9.1
    - python >=3.7
    - readtime >=2.0
    - regex >=2022.4.24
    - requests >=2.26

test:
  imports:
    - material
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://squidfunk.github.io/mkdocs-material/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Material Design theme for mkdocs
  doc_url: https://squidfunk.github.io/mkdocs-material/
  dev_url: https://squidfunk.github.io/mkdocs-material/customization/

extra:
  recipe-maintainers:
    - monaldoj
    - marcelotrevisani
    - thewchan
